update emacs and tmux settings

diff --git a/.bin/e b/.bin/e
--- a/.bin/e
+++ b/.bin/e
@@ -1,19 +1,20 @@
 #!/bin/sh
-if ! $(which emacsclient) -e 1 > /dev/null; then
+if ! which -s emacsclient; then
+    echo 'emacsclient not found'
     exit
 fi
 
-# open files
-if [ $# -eq 0 ]; then
-    $(which emacsclient) -n .
+if [ "$1" == "-" ]; then
+    # read from STDIN
+    TMP="$(mktemp /tmp/stdin-XXX)"
+    cat > $TMP
+    emacsclient -n $TMP
+    rm $TMP
 else
-    $(which emacsclient) -n "$@"
-fi
-
-# find from tmux windows
-if [ -n $TMUX ]; then
-    EMACS_WINDOW_INDEX=$(tmux list-windows -F '#{window_index}:#{window_name}' | perl -ne '/^(\d+):emacs$/ and print $1 and exit')
-    if ! [ -z $EMACS_WINDOW_INDEX ]; then
-        tmux select-window -t $EMACS_WINDOW_INDEX
+    # open file or current directory
+    if [ $# -eq 0 ]; then
+        emacsclient -n .
+    else
+        emacsclient -n "$@"
     fi
 fi
